#!/bin/sh
TAHOMA2D_BASE=$(dirname "$0")/usr

if [ ! -d $HOME/.config/Tahoma2D ]; then
    mkdir -p $HOME/.config/Tahoma2D
fi

if [ ! -d $HOME/.config/Tahoma2D/stuff ]; then
    cp -r $TAHOMA2D_BASE/share/tahoma2d/stuff $HOME/.config/Tahoma2D
fi

if [ ! -e $HOME/.config/Tahoma2D/SystemVar.ini ]; then
    cat << EOF > $HOME/.config/Tahoma2D/SystemVar.ini
[General]
TAHOMA2DROOT="$HOME/.config/Tahoma2D/stuff"
TAHOMA2DPROFILES="$HOME/.config/Tahoma2D/stuff/profiles"
TAHOMA2DCACHEROOT="$HOME/.config/Tahoma2D/stuff/cache"
TAHOMA2DCONFIG="$HOME/.config/Tahoma2D/stuff/config"
TAHOMA2DFXPRESETS="$HOME/.config/Tahoma2D/stuff/fxs"
TAHOMA2DLIBRARY="$HOME/.config/Tahoma2D/stuff/library"
TAHOMA2DPROFILES="$HOME/.config/Tahoma2D/stuff/profiles"
TAHOMA2DPROJECTS="$HOME/.config/Tahoma2D/stuff/projects"
TAHOMA2DROOT="$HOME/.config/Tahoma2D/stuff"
TAHOMA2DSTUDIOPALETTE="$HOME/.config/Tahoma2D/stuff/studiopalette"
EOF
fi

export LD_LIBRARY_PATH=${TAHOMA2D_BASE}/lib/tahoma2d:${LD_LIBRARY_PATH}

IFS=:
for LIBPATH in $LD_LIBRARY_PATH
do
  if [ "$CAMLIBS" = "" -a -d $LIBPATH/libgphoto2 ]
  then
     export CAMLIBS=`find $LIBPATH/libgphoto2 -mindepth 1 -type d`
  fi

  if [ "$IOLIBS" = "" -a -d $LIBPATH/libgphoto2_port ]
  then
     export IOLIBS=`find $LIBPATH/libgphoto2_port -mindepth 1 -type d`
  fi
done
unset IFS

echo "CAMLIBS: $CAMLIBS"
echo "IOLIBS: $IOLIBS"

exec $TAHOMA2D_BASE/bin/Tahoma2D "$@"
